# Generated by Django 6.0.3 on 2026-03-28 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_tanggal_lahir'),
        ('deeds', '0002_deed_file_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honorarium', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jasa Notaris')),
                ('ppn_jasa', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='PPN 11%')),
                ('pph', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PPh (Penjual)')),
                ('bphtb', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='BPHTB (Pembeli)')),
                ('pnbp', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='PNBP/Biaya BPN')),
                ('biaya_lain', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biaya Tambahan')),
                ('keterangan_biaya_lain', models.CharField(blank=True, max_length=255, null=True)),
                ('is_pph_valid', models.BooleanField(default=False, verbose_name='PPh Sudah Valid')),
                ('is_bphtb_valid', models.BooleanField(default=False, verbose_name='BPHTB Sudah Valid')),
                ('total_tagihan', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('terbayar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('UNPAID', 'Belum Bayar'), ('PARTIAL', 'Cicil'), ('PAID', 'Lunas')], default='UNPAID', max_length=10)),
                ('jatuh_tempo', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='clients.client')),
                ('deed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='deeds.deed')),
            ],
        ),
    ]
