# Generated by Django 6.0.3 on 2026-03-18 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_tanggal_lahir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_akta', models.CharField(max_length=100, unique=True)),
                ('jenis_akta', models.CharField(max_length=50)),
                ('kategori', models.CharField(choices=[('PPAT', 'Akta PPAT'), ('NOTARIS', 'Akta Notaris')], max_length=10)),
                ('tanggal_buat', models.DateField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('file_akta', models.FileField(blank=True, null=True, upload_to='deeds/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deeds', to='clients.client')),
            ],
        ),
    ]
