# Generated by Django 6.0.3 on 2026-03-22 18:16

import apps.deeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='file_scan',
            field=models.FileField(blank=True, null=True, upload_to=apps.deeds.models.get_upload_path),
        ),
    ]
