# Generated by Django 6.0.3 on 2026-03-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0002_deed_file_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='deed',
            name='nilai_transaksi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
