# Generated by Django 6.0.3 on 2026-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0003_deed_nilai_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deed',
            name='nilai_transaksi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nilai transaksi yang tertulis di Akta', max_digits=20),
        ),
    ]
