# Generated by Django 6.0.3 on 2026-04-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0004_alter_deed_nilai_transaksi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='file_akta',
        ),
        migrations.AddField(
            model_name='deed',
            name='kedudukan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='modal_dasar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='deed',
            name='modal_disetor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='deed',
            name='nama_perseroan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deed',
            name='jenis_akta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deed',
            name='nilai_transaksi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Nilai transaksi untuk akta jual beli/PPAT', max_digits=20),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(choices=[('DIREKTUR_UTAMA', 'Direktur Utama'), ('DIREKTUR', 'Direktur'), ('KOMISARIS', 'Komisaris')], max_length=50)),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='deeds.deed')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nik', models.CharField(max_length=20)),
                ('jumlah_saham', models.IntegerField()),
                ('total_nominal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='deeds.deed')),
            ],
        ),
    ]
