# Generated by Django 6.0.3 on 2026-04-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0005_remove_deed_file_akta_deed_kedudukan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deed',
            name='modal_disetor',
        ),
        migrations.RemoveField(
            model_name='deed',
            name='modal_dasar',
        ),
        migrations.RemoveField(
            model_name='deed',
            name='nama_perseroan',
        ),
        migrations.AddField(
            model_name='deed',
            name='jam_buat',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='deed',
            name='nama_entitas',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='persentase',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='deed',
            name='nilai_transaksi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='management',
            name='jabatan',
            field=models.CharField(choices=[('DIREKTUR_UTAMA', 'Direktur Utama'), ('DIREKTUR', 'Direktur'), ('KOMISARIS_UTAMA', 'Komisaris Utama'), ('KOMISARIS', 'Komisaris')], max_length=50),
        ),
        migrations.CreateModel(
            name='DeedPT',
            fields=[
                ('deed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='deeds.deed')),
                ('modal_dasar', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('modal_ditempatkan', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('modal_disetor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('nilai_par_saham', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'verbose_name': 'Akta PT',
                'verbose_name_plural': 'Akta PT',
            },
            bases=('deeds.deed',),
        ),
    ]
