# Generated by Django 6.0.3 on 2026-03-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK KTP')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat_ktp', models.TextField()),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_perusahaan', models.BooleanField(default=False, verbose_name='Mewakili Badan Hukum?')),
                ('nama_perusahaan', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_ktp', models.ImageField(blank=True, null=True, upload_to='ktp_scans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Penghadap',
                'verbose_name_plural': 'Daftar Penghadap',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField()),
                ('tanggal_kontak', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client')),
            ],
        ),
    ]
